version: '2'
services:
  wordpress:
    container_name: wordpress-hope21
    image: sujin2f/wordpress:latest
    external_links:
      - mariadb:mysql
      - mailhog
    restart: always
    environment:
      VIRTUAL_HOST: hope21.test
      WORDPRESS_DB_NAME: hope21.test
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
      TZ: America/Toronto
    volumes:
      - ../../storage/sujin/plugins:/var/www/html/wp-content/plugins
      - ../../storage/sujin/uploads:/var/www/html/wp-content/uploads
      - ./:/var/www/html/wp-content/themes/hope21
    ports:
      - 80
    networks:
      - local_default
networks:
  local_default:
    external: true
